Create domain.md
spdx/spdx-3-model pull request #109
Opened 2023-03-07 03:00 UTC by rgopikrishnan91

create properties file for domain @zvr @kestewart @lumjjb

2023-03-29 22:03 UTC, kestewart requested changes

2023-03-29 22:03 UTC, kestewart commented on model/AI/domain.md
"Field captures theDescribe" - doesn't make sense to me.   Clarify, and add proper punctuation to the Summary.

2023-03-30 00:03 UTC, bennetkl approved these changes
Suggest changing Natural Language Processing (NLP).  This is not a blocker

2023-03-30 15:04 UTC, kestewart approved these changes

2023-03-30 15:05 UTC, merged