Create autonomyType.md
spdx/spdx-3-model pull request #110
Opened 2023-03-07 03:01 UTC by rgopikrishnan91

create a properties file for autonomyType @zvr @kestewart @lumjjb

2023-03-17 09:25 UTC, maxhbr requested changes

2023-03-17 09:25 UTC, maxhbr commented on model/AI/Properties/autonomyType.md
> +# autonomy
the title needs to be consistent:

```suggestion
# autonomyType
```

2023-03-29 21:49 UTC, kestewart requested changes
Fix capitalization of  autonomyType to AutonomyType, to be consistent.

2023-03-29 21:56 UTC, rgopikrishnan91 commented
It should still be autonomyType --since all fields in properties are named with camel case (where first letter is lower case), for the data types defined in Vocabulary are named with camel case (but the first letter also being in upper case). autonomyType is a property of the data type (PresenceType).

@zvr could you please confirm this rationale?

2023-03-30 00:01 UTC, bennetkl approved these changes
Looks good.

2023-03-30 15:16 UTC, merged