add External ID/Ref related descriptions
spdx/spdx-3-model pull request #120
Opened 2023-03-09 11:39 UTC by armintaenzertng

This is an attempt to fill in the missing descriptions in the Core profile. Where possible, I tried to copy from the SPDX-2.3 specification.
Please note that this does not aim to be the final solution but will hopefully start discussions on possibly controversial points.

2023-03-10 03:44 UTC, goneall approved these changes
Just a cursory review, mostly of the text - but it LGTM.

I agree with the changes in the property names.

Thanks @armintaenzertng

2023-03-17 09:29 UTC, maxhbr requested changes
`externalIdentifier` -> `externalIdentifiers`

2023-03-17 09:29 UTC, maxhbr commented on model/Core/Properties/externalIdentifiers.md
> +- name: externalIdentifier
this also needs to be consistent
```suggestion
- name: externalIdentifiers
```

2023-03-17 09:30 UTC, maxhbr commented
same for `externalReference` -> `externalReferences`

2023-03-22 00:05 UTC, maxhbr approved these changes
LGTM

2023-03-28 17:21 UTC, goneall commented
Reviewed and approved on the 28 Mar 2023 tech call

2023-03-28 17:21 UTC, merged