add Software related descriptions
spdx/spdx-3-model pull request #122
Opened 2023-03-09 16:26 UTC by armintaenzertng

This is an attempt to fill in the missing descriptions in the Software profile. Where possible, I tried to copy from the SPDX-2.3 specification.
Please note that this does not aim to be the final solution but will hopefully start discussions on possibly controversial points.

This misses descriptions for
- packageUrl
- contentIdentifier
- File

which I was not sure about their actual definition.

2023-03-10 04:00 UTC, goneall requested changes
A few suggested changes.

Thanks @armintaenzertng for kicking this off

2023-03-10 08:53 UTC, armintaenzertng commented on model/Software/Classes/Sbom.md
> +A container for a grouping of SPDX-3.0 content characterizing details about a software product.
done

2023-03-10 08:53 UTC, armintaenzertng commented on model/Software/Properties/contentType.md
> +This field is a reasonable estimation of the content type of the Element, from a developer perspective.
done

2023-03-10 22:00 UTC, goneall approved these changes
LGTM

2023-03-28 16:25 UTC, merged

2023-03-28 16:26 UTC, goneall commented
Reviewed and approved on 28 Mar 2023 tech call