Create anonymizationMethodUsed.md
spdx/spdx-3-model pull request #154
Opened 2023-03-30 20:30 UTC by rgopikrishnan91

Hi @kestewart @bennetkl Please review

2023-03-31 20:06 UTC, kestewart requested changes
Fix typo "anonymyze" in summary. 
In metadata name shouldn't be sensors.

2023-04-04 09:41 UTC, armintaenzertng commented on model/Dataset/Properties/anonymizationMethodUsed.md
> +- Range: xsd: string
```suggestion
- Range: xsd:string
```

2023-04-04 09:41 UTC, armintaenzertng commented on model/Dataset/Properties/anonymizationMethodUsed.md
> +The field describes the anonymization methods used. If multiple anonymization methods are used, each anonymization method is specified in a new line.
Same comment as [here](https://github.com/spdx/spdx-3-model/pull/163#discussion_r1156985033).
That is, `anonymizationMethodUsed` has arbitrary cardinality when used in the [Dataset class](https://github.com/spdx/spdx-3-model/blob/dataset-profile/model/Dataset/Classes/Dataset.md), so we should not discuss multiple values in this property.

2023-04-11 01:14 UTC, bennetkl reviewed
Typically with AI applications, data anonymization is done by creating a mirror image of the dataset and then  implementing alteration strategies, such as character shuffling, encryption, term, or character substitution.     This field is meant to capture all the strategies used to 'change' the dataset

2023-04-11 01:24 UTC, goneall commented
Superseded by PR #185 which includes feedback form this PR

2023-04-11 01:24 UTC, closed without merging