Create senstivePersonalInformationType.md
spdx/spdx-3-model pull request #162
Opened 2023-03-30 20:42 UTC by rgopikrishnan91

Hi @kestewart and @bennetkl please review

2023-03-31 20:21 UTC, kestewart requested changes
name: sensors ??   doesn't look quite right.

2023-04-04 09:38 UTC, armintaenzertng commented on model/Dataset/Properties/senstivePersonalInformationType.md
The file name (and PR name) has a typo.

2023-04-05 21:35 UTC, kestewart commented
@rgopikrishnan91 - can you fix?

2023-04-11 01:16 UTC, goneall commented
Superseded by PR #184 which includes feedback from @armintaenzertng

2023-04-11 01:16 UTC, closed without merging

2023-04-11 01:17 UTC, bennetkl approved these changes
Please fix typo in file name