Create sensors.md
spdx/spdx-3-model pull request #163
Opened 2023-03-30 20:44 UTC by rgopikrishnan91

Hi @kestewart  and @bennetkl please review

2023-03-31 20:23 UTC, kestewart requested changes
Fix typo "ina" possibly should be " on a"

2023-04-02 13:13 UTC, kestewart commented
Also, fix typo: "where"  should be "were" in Summary

2023-04-04 09:37 UTC, armintaenzertng commented on model/Dataset/Properties/sensors.md
> +Each sensor and their callibration value in form Sensor:calibration is noted. If multiple sensors are used, each sensor and thier callibration value is noted ina new line
`sensors` has arbitrary cardinality when used in the [`Dataset` class](https://github.com/spdx/spdx-3-model/blob/dataset-profile/model/Dataset/Classes/Dataset.md), so we should not discuss multiple values in this property.

2023-04-05 13:48 UTC, bennetkl reviewed
Seems like we should use map, we can discuss in today's AI sbom meeting and I can provide description in Gopi's absense

2023-04-05 21:33 UTC, kestewart commented
Discussed in call, and we'll apply mapping.   This should not be a blocker though for merging.     After a class is identified, we'll apply in a single pass.

2023-04-11 01:31 UTC, goneall commented
Superseded by PR #187 which includes feedback with the exception of the map which is referenced in Issue #186

2023-04-11 01:31 UTC, closed without merging