Security profile: Add basic structure as md-files
spdx/spdx-3-model pull request #168
Opened 2023-03-31 15:28 UTC by armintaenzertng

I converted the structure found in the `security-profile.png` into model md-files.

Three issues arise:
- [ ] #165 
- [ ] #166 
- [ ] #167

2023-03-31 22:59 UTC, maxhbr commented
Maybe helpful: this is a visualization generated from the markdown data on https://github.com/armintaenzertng/spdx-3-model/commit/2e8131b449bc898a819280c51a6016921e150e20:

![Security Profile](https://user-images.githubusercontent.com/1187050/229247049-84e2ba44-32e2-4a3f-9f77-c6da76d68e1a.svg)

2023-04-05 18:48 UTC, jeff-schutt requested changes
Added links to relevant specifications and/or documentation

2023-04-05 18:48 UTC, jeff-schutt commented on model/Security/Classes/EpssVulnerabilityCategorization.md
> +An EpssVulnerabilityCategorization is TODO
```suggestion
[https://www.first.org/epss/model](https://www.first.org/epss/model)
```

2023-04-05 18:48 UTC, jeff-schutt commented on model/Security/Classes/CvssV2VulnerabilityCategorization.md
> +A CvssV2VulnerabilityCategorization is TODO
```suggestion
[https://www.first.org/cvss/v2/guide](https://www.first.org/cvss/v2/guide)
```

2023-04-05 18:48 UTC, jeff-schutt commented on model/Security/Classes/CvssV3VulnerabilityCategorization.md
> +A CvssV3VulnerabilityCategorization is TODO
```suggestion
[https://www.first.org/cvss/v3.1/specification-document](https://www.first.org/cvss/v3.1/specification-document)
```

2023-04-05 18:48 UTC, jeff-schutt commented on model/Security/Classes/ExploitCatalogVulnerabilityCategorization.md
> +# ExploitCatalogVulnerabilityCategorization
```suggestion
# KnownExploitedVulnerabilitiesCatalogCategorization
```

2023-04-05 18:48 UTC, jeff-schutt commented on model/Security/Classes/ExploitCatalogVulnerabilityCategorization.md
> +An ExploitCatalogVulnerabilityCategorization is TODO
[https://www.cisa.gov/known-exploited-vulnerabilities-catalog](https://www.cisa.gov/known-exploited-vulnerabilities-catalog)

2023-04-06 07:17 UTC, armintaenzertng commented
Thanks for your suggestions, @jeff-schutt! I added them in.

2023-04-07 00:53 UTC, goneall commented
@tsteenbe @jeff-schutt - with the suggestions merged in, do you want to go ahead and merge this PR so we can use it as a starting point for any additional review/changes?

2023-04-13 00:02 UTC, goneall approved these changes
Since this is going into the security profile branch and not the main branch, I suggest we go ahead and merge it so we can use it as a base to fill in the missing "TODO"'s.  Once merged, we should create issues from some of the comments (e.g. the property is used in multiple locations).

2023-05-02 09:13 UTC, merged