External properties restrictions
spdx/spdx-3-model pull request #170
Opened 2023-04-02 10:24 UTC by zvr

Adds restrictions to external properties

The way to specify restrictions to external properties is:

- refer to the external property as a complete path of /{profile}/{class}/{property}
- add the shape defintion, which overwrites the original one.

Realistically, the restrictions will mostly be optional properties becoming mandatory,
i.e., minCount changing from 0 to 1.

2023-04-02 17:50 UTC, goneall approved these changes
LGTM

2023-04-03 07:51 UTC, maxhbr requested changes

2023-04-03 07:51 UTC, maxhbr commented on model/Core/Classes/SpdxDocument.md
> +- /Core/Element/name
you use `/` as seperator and in other places we use `:`:

https://github.com/spdx/spdx-3-model/blob/01360996d37c1d913f3d15e2d5911ace182ed200/model/Software/Classes/File.md?plain=1#L16

Can we make this consistent?

2023-04-03 07:57 UTC, maxhbr commented on model/Core/Classes/SpdxDocument.md
> +- /Core/Element/name
It would probably be best, to align with the way rdf is referencing the properties.

2023-04-03 17:09 UTC, goneall approved these changes
LGTM

2023-04-04 16:44 UTC, merged