Usage profile
spdx/spdx-3-model pull request #191
Opened 2023-04-11 09:03 UTC by yoshi-i

Model descriptions with drawio and supplemental pdf document of Usage Profile

Signed-off-by: Yoshiyuki Ito <yoshiyuki.ito.ub@renesas.com>

2023-04-11 14:56 UTC, maxhbr requested changes, later dismissed

2023-04-11 19:42 UTC, swinslow commented
Hello,

It doesn't look like there is a way to comment inline in the PDF itself, so I'm replying with a couple of thoughts here.

For slide 6 "Terms of Use for these deliverables": if this is about a contractual limitation on use, wouldn't that be more appropriate to include a licensing profile section with a `LicenseRef-` ID, pointing to the text of the contract? I don't think a separate field to refer to a contract that imposes different limitations on use of software would be helpful, since it would require an SBOM recipient to look in two separate places to understand the license limitations.

For slide 7 "Expiration date and time OR Expiration event": similarly, it would be helpful to have more explanation to understand what is "expiring" in this situation. I assume that it wouldn't be either the SBOM itself, or the license to use the software. Is there something else that is "expiring"?

2023-04-12 01:07 UTC, yoshi-i commented on doc/UsageProfile.svg
@maxhbr -san, It was overwritten by my operation mistake. I've committed correct one.

2023-04-14 18:09 UTC, goneall approved these changes

2023-04-14 18:11 UTC, goneall requested changes
I just saw @maxhbr comment - indeed the draw.io file is HTML rather than the draw.io data which can be downloaded.

2023-04-19 10:05 UTC, yoshi-i commented
> I just saw @maxhbr comment - indeed the draw.io file is HTML rather than the draw.io data which can be downloaded.

Sorry, I've re-committed at #38f3040 for that drawio file.

2023-04-20 01:05 UTC, goneall approved these changes
LGTM - Thanks @yoshi-i

2023-04-24 01:08 UTC, goneall commented
@maxhbr - pls review and if OK, we can merge

2023-04-24 19:10 UTC, maxhbr commented on doc/UsageProfile.svg
I do not understand the `USAGE OPERATOR`, are there some examples?

2023-04-24 19:21 UTC, maxhbr requested changes

2023-04-24 19:21 UTC, maxhbr commented on doc/UsageProfile.svg
This uses the DESCRIBES relation, but that is (at least in 2.3) defined as "Is to be used when SPDXRef-DOCUMENT describes SPDXRef-A." with the example "An SPDX document WildFly.spdx describes package ‘WildFly’. Note this is a logical relationship to help organize related items within an SPDX document that is mandatory if more than one package or set of files (not in a package) is present.". Not sure if it is valid in this usecase.

2023-04-24 19:21 UTC, maxhbr commented on doc/UsageProfile.svg
This shows a specific way of how licensing information is expressed, which might not align with the actual future of the licensing profile. Maybe this could be made transparent

2023-04-24 19:21 UTC, maxhbr commented on doc/UsageProfile.svg
I think we always use singular: 
* `Deliverables` -> `Deliverable`
* `comments` -> `comment`

2023-04-24 19:21 UTC, maxhbr commented on doc/UsageProfile.svg
The `AND` and `OR` looks very similar to license expressions and might cause confusion.

2023-04-24 19:21 UTC, maxhbr commented on doc/UsageProfile-20230328_en.pdf
Could you maybe instead provide some file that can be edited and further improved instead of a PDF?

2025-10-10 18:20 UTC, goneall commented
The operations profile is now picking up some of these fields - I'm going to close this for now - @yoshi-i - If you would like to reopen, please take a look at the operations profile branch first and see if we still need the Usage profile.

2025-10-10 18:20 UTC, closed without merging