AI profile: use DictionaryEntry where appropriate
spdx/spdx-3-model pull request #197
Opened 2023-04-14 12:07 UTC by armintaenzertng

The AI profile uses some key-value-like properties that can make use of the structure provided by the new `DictionaryEntry` class.

2023-04-14 18:01 UTC, goneall requested changes
@armintaenzertng Can you remove some of the description text that referred to the old text formats?

2023-04-14 18:01 UTC, goneall commented on model/AI/Properties/metricsDecisionThresholds.md
Same comment as above - suggest removing:

```
This field records the decision threshold in comma separated values. E.g., metric_1:decsion_threshold, metric_2:decision threshold. If there are multiple models each line represents each model’s metrics and decision threshold. Each decision threshold should match with the metrics field defined in the AI Package.
```

2023-04-17 06:12 UTC, armintaenzertng commented
@goneall, I fully agree with your suggestions, but I did not include them in this PR as they were already handled in another one. I rebased this PR now so it includes the reworked descriptions,

2023-04-17 13:09 UTC, goneall approved these changes
Thanks @armintaenzertng

2023-04-19 21:34 UTC, kestewart approved these changes
Changes match discussion.

2023-04-19 21:37 UTC, rgopikrishnan91 reviewed
Looks good to me. I approve the changes

2023-04-19 21:38 UTC, merged