update security suppliedBy.md range to point to core suppliedby.md
spdx/spdx-3-model pull request #488
Opened 2023-08-29 15:51 UTC by jeff-schutt

3rd change to resolve https://github.com/spdx/spdx-3-model/issues/436 

Intent is to have the suppliedBy property in the security profile reuse the suppliedBy property defined in the Core profile to avoid duplication of definitions.

2023-08-29 16:18 UTC, jeff-schutt commented
In #436 I see Gary made a different suggestion [here](https://github.com/spdx/spdx-3-model/issues/436#issuecomment-1673619564). Review requested to determine what change is needed.

2023-09-06 18:18 UTC, goneall requested changes

2023-09-06 18:18 UTC, goneall commented on model/Security/Classes/VulnAssessmentRelationship.md
>  - suppliedBy
```suggestion
- /Core/suppliedBy
```

2023-09-06 18:18 UTC, goneall commented on model/Security/Classes/VulnAssessmentRelationship.md
> +  - type: /Core/SuppliedBy
```suggestion
  - type: /Core/Agent
```

2023-09-06 18:26 UTC, goneall approved these changes
LGTM

2023-09-06 18:28 UTC, tsteenbe commented
Discussed in the Defects meeting of Sept 6th, 2023 by @goneall  @jeff-schutt  @rnjudge @tsteenbe - MarkDown encoding for this pull request is now correct but spec parser needs to be updated by @goneall  before this can be merged.

2023-09-06 18:50 UTC, goneall commented
Turns out I was wrong on the analysis of the CI failure - this is failing due to the Jinja changes - not due to handling /Core.

I tested this change locally on my machine with an earlier version of the spec-parser and it works, so this is safe to merge.

2023-09-06 19:10 UTC, goneall commented
Just a note: this is a fix for the CI failure: https://github.com/spdx/spec-parser/pull/69

2023-10-17 17:05 UTC, zvr approved these changes

2023-11-28 18:16 UTC, rnjudge commented
LGTM

2023-11-28 18:16 UTC, kestewart approved these changes
Reviewed on call.   Looks good.

2023-11-28 18:21 UTC, goneall commented
To be merged once we merge the new parser - cc: @zvr

2023-12-11 23:37 UTC, goneall commented
The parser has been updated - merging...

2023-12-11 23:37 UTC, merged