add CvssV4VulnAssessmentRelationship.md and CvssSeverityType.md
spdx/spdx-3-model pull request #501
Opened 2023-09-28 00:05 UTC by jeff-schutt

Initial draft of changes to support CVSS version 4

CC: @rnjudge @tsteenbe @goneall

2023-09-29 16:50 UTC, goneall requested changes
Just a few things I noticed.

Also, as a reminder, we'll need to update the[ severity property range](https://github.com/spdx/spdx-3-model/blob/f5976aee78e3c1bc2024eca8631a7d20281ffb6c/model/Security/Properties/severity.md?plain=1#L18) to be `CvssSeverityType`, the [CvssV2VulnAssessmentRelationship severity type](https://github.com/spdx/spdx-3-model/blob/f5976aee78e3c1bc2024eca8631a7d20281ffb6c/model/Security/Classes/CvssV2VulnAssessmentRelationship.md?plain=1#L75C5-L75C5) to `CvssSeverityType` and the [CvssV3VulnAssessmentRelationship severity type](https://github.com/spdx/spdx-3-model/blob/f5976aee78e3c1bc2024eca8631a7d20281ffb6c/model/Security/Classes/CvssV3VulnAssessmentRelationship.md?plain=1#L78) to `CvssSeverityType`

2023-09-29 16:50 UTC, goneall commented on model/Security/Classes/CvssV4VulnAssessmentRelationship.md
> +- Score
```suggestion
- score
```

2023-09-29 16:50 UTC, goneall commented on model/Security/Classes/CvssV4VulnAssessmentRelationship.md
> +- Severity
```suggestion
- severity
```

Properties should start with lower case

2023-09-29 16:50 UTC, goneall commented on model/Security/Classes/CvssV4VulnAssessmentRelationship.md
> +  "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N",
From a quick glance, should this start with "CVSS:4"?

2023-10-05 21:14 UTC, jeff-schutt commented on model/Security/Classes/CvssV4VulnAssessmentRelationship.md
> +  "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N",
Addressed in latest commit, thanks!

2023-10-05 22:22 UTC, goneall approved these changes
LGTM

2023-10-11 18:19 UTC, kestewart approved these changes
Looks good to me.

2023-10-11 18:22 UTC, jeff-schutt reviewed
Minor typo

2023-10-11 18:22 UTC, jeff-schutt commented on model/Security/Classes/CvssV4VulnAssessmentRelationship.md
> +    }
```suggestion
```

2023-10-11 18:26 UTC, merged