Initial definition of Extension namespace
spdx/spdx-3-model pull request #503
Opened 2023-09-29 17:20 UTC by sbarnum

2023-09-29 17:31 UTC, sbarnum commented
It looks like the checks on this may have failed due to the inclusion of an "Remote Classes" section within the extension.md property specification.
This is a new concept but is required if we want Extension to be in a separate profile/namespace.
Typically all SHACL NodeShapes (with accompanying property shapes) will be defined directly from the Class specification file.
In this case to avoid having to specify the property shape for 'extension' on the Element class in the core namespace which would invalidate the concept of Extension as a separate profile/namespace, there needs to be an additional SHACL NodeShape targeting the Element class and asserting the property shape (no cardinality constraints; only path name, nodekind and class) for the 'element' property but it must be defined in the Extension profile/namespace.
To accomplish this I introduced the nomenclature of "Remote Classes" as a specification section on some properties that asserts SHACL shapes that need defined within the local profile/namespace for that property on the referenced "remote" (outside the local namespace) Class. While the case of 'element' property on Element is zer0-to-many and thus has no cardinality constraints other potential uses of Remote Classes in the future may.

2023-09-29 18:17 UTC, goneall commented
@sbarnum - thanks for writing this up.  On the remote classes, we can open a PR for the [spec-parser](https://github.com/spdx/spec-parser) to understand the section.

Currently, the spec-parser generates a model file with OWL and SHACL and a separate JSON-LD context file.

Can you document what should be added to these files?  We can then update the spec-parser unless there are objections to the format.

2023-09-29 18:18 UTC, goneall commented
@sbarnum - could you also add a profile.md for Extension which describes the profile?

2023-09-30 08:55 UTC, zvr commented
I'm not sure I understood what "Remote Classes" is about.

Are you saying that this PR introduces the property `extension` (an object property with range of `Extension`) and this property is on the `Core/Element` class?

If yes, the way we have done it until now is to actually modify the `Core/Element` class.

2023-10-05 16:00 UTC, sbarnum commented
> I'm not sure I understood what "Remote Classes" is about.
> 
> Are you saying that this PR introduces the property `extension` (an object property with range of `Extension`) and this property is on the `Core/Element` class?
> 
> If yes, the way we have done it until now is to actually modify the `Core/Element` class.

Yes. This PR introduces the property 'extension' (an object property with range of `Extension`) and this property would apply on the `Core/Element` class however it is defined within a separate profile with a separate namespace and therefore cannot be expressed as a modification to the `Core/Element` class specification in core.
If it was defined as a modification to the `Core/Element` class specification in core then you could not separate conformance to the core profile without conformance to the Extension profile from conformance to the core profile with conformance to the Extension profile.
By specifying `Core/Element` as a 'Remote Class' on the `extension` specification within the Extension profile/namespace it can be used to generate a separate SHACL shape in the separate SHACL file for the Extension profile/namespace and only be applied when the content claims conformance to the Extension profile.

2023-10-10 15:31 UTC, sbarnum commented
> @sbarnum - could you also add a profile.md for Extension which describes the profile?

I am unclear where this would go and what i should use as an exemplar of what you are looking for.
Could you outline a little more what you are looking for?

2023-11-07 18:10 UTC, goneall commented
@zvr and @sbarnum to sync up and resolve

2023-12-27 10:17 UTC, zvr requested changes
Minor fixes to the way we reference other namespaces, and then it can be merged.

2023-12-27 10:17 UTC, zvr commented on model/Core/Classes/Element.md
> +  - type: Extension/Extension
```suggestion
  - type: /Extension/Extension
```

2023-12-27 10:17 UTC, zvr commented on model/Core/Properties/extension.md
> +- Range: Extension
```suggestion
- Range: /Extension/Extension
```

2023-12-28 13:42 UTC, zvr approved these changes

2023-12-28 18:49 UTC, goneall commented
It looks like the spec-parser is failing with this PR.  I'll see if I can narrow down the issue.

2023-12-28 19:14 UTC, goneall commented
It looks like this is caused by having a profile by the same name as a property.

I created https://github.com/spdx/spec-parser/issues/82 in the spec parser.

@zvr - any ideas how to fix?

We could work around this by either renaming the property or renaming the profile.

2023-12-28 20:38 UTC, zvr commented
@goneall the new parser, completely rewritten from scratch, does not have such issues.

2023-12-28 21:40 UTC, goneall commented
> the new parser, completely rewritten from scratch, does not have such issues.

Where is the new parser implemented?

2023-12-28 22:30 UTC, zvr commented
> Where is the new parser implemented?

https://github.com/spdx/spec-parser/tree/new-parser

2023-12-29 00:03 UTC, goneall commented
@zvr - how soon before the new spec-parser is ready?  I noticed it isn't processing args yet - so I wasn't able to test with this branch of the model.

2024-01-16 17:59 UTC, kestewart commented
per Jeff on the call,  the new spec parser issues should now be resolved.

2024-01-23 19:00 UTC, goneall approved these changes
LGTM

2024-01-23 19:00 UTC, merged