Fixing typos/syntax errors
spdx/spdx-3-model pull request #520
Opened 2023-10-20 11:47 UTC by zvr

This fixes various issues that the (new) spec-parser points out.

Among them:
- mismatches between "name" property and file name and title
- vocabularies entries not in lowerCamelCase
- missing sections ("Summary" in most/all cases)
- empty sections ("Properties" in most/all cases)
- ... and probably some others I don't remember

2023-10-20 16:07 UTC, goneall requested changes
See comment - suggest moving one of the changes to a separate PR unless it causes the spec-parser to fail.

2023-10-20 16:07 UTC, goneall commented on model/Security/Vocabularies/CvssSeverityType.md
This change is consistent with the naming conventions of SPDX, however, the security profile is attempting to have the resultant JSON Schema match the CVSS schema and this change will make them different.

Since there is a direct mapping, I'm OK with using the SPDX conventions, but @jeff-schutt @tsteenbe @rnjudge should also review

I would move this into a separate PR to give the security team time to review.  If the current state causes the spec-parser to fail, then I would suggest merging it in and adding a new issue to discuss the incompatibility.

2023-10-20 20:50 UTC, zvr commented on model/Security/Vocabularies/CvssSeverityType.md
This is about entries for a vocabulary, which are automatically converted to IRIs of individuals in RDF.

The process of generating the JSON Schema already does many transformations, as it's not a 1:1 correspondence. If the requirement is to have them appear as upper-case strings, this is easily done at that stage.

2023-10-20 23:18 UTC, goneall commented on model/Security/Vocabularies/CvssSeverityType.md
> The process of generating the JSON Schema already does many transformations, as it's not a 1:1 correspondence. If the requirement is to have them appear as upper-case strings, this is easily done at that stage.

Based on the above, it sounds like we can go ahead and move forward with this PR pending one more review.

I'll leave it up to the security profile group to decide if it is important to maintain uppercase.

2023-10-20 23:18 UTC, goneall approved these changes

2023-10-21 05:43 UTC, kestewart approved these changes
Apply these changes, but then let's get the security team to review.

They'll need to update their examples.

2023-10-21 05:43 UTC, kestewart commented on model/Security/Vocabularies/CvssSeverityType.md
ok, let's apply this, and then ask them to do a pass.

2023-10-21 05:43 UTC, merged