Update Dataset.md to add license restrictions
spdx/spdx-3-model pull request #537
Opened 2023-10-25 20:26 UTC by rgopikrishnan91

@kestewart Please review if the added constraints look okay. This is in accordance with my best interpretation of #462

2023-10-25 21:06 UTC, maxhbr requested changes

2023-10-25 21:06 UTC, maxhbr commented on model/Dataset/Classes/Dataset.md
>  - /Software/SoftwareArtifact/primaryPurpose
this should be in `## External properties restrictions` ?

2023-10-26 07:57 UTC, zvr requested changes
Please use the format of #524 to express restrictions in a separate file,

2023-11-01 20:40 UTC, rgopikrishnan91 commented
@zvr Can you please review if this is conformant now?

2023-11-01 21:08 UTC, rgopikrishnan91 commented
Added the necessary changes to #536 . So closing this seperate PR

2023-11-01 21:08 UTC, closed without merging