Add missing software purposes for CDX 1.5 compat
spdx/spdx-3-model pull request #555
Opened 2023-11-14 17:51 UTC by puerco

This commit adds two new software purposes: `deviceDriver` and `platform` to keep the compatibility of this field with the recent CycloneDX 1.5 release.

/cc @kestewart @rnjudge @JPEWdev

Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>

2023-11-14 18:14 UTC, kestewart requested changes
Couple of minor tweaks requested for conistency.

2023-11-14 18:14 UTC, kestewart commented on model/Software/Vocabularies/SoftwarePurpose.md
> +- deviceDriver: the referred element represents software that controls hardware devices
Can we keep standardized with the others?   s/the referred element/the Element/ ?

2023-11-14 18:14 UTC, kestewart commented on model/Software/Vocabularies/SoftwarePurpose.md
> +- platform: The element represents a runtime environment
s/element/Element/

2023-11-14 21:12 UTC, puerco commented
@kestewart ok, fixed it to mimic the language in the other lines !

2023-11-14 22:58 UTC, kestewart approved these changes
Thanks!  Aligns with the others now.

2023-11-15 00:07 UTC, puerco commented
Merge conflicts resolved :shipit:

2023-11-15 00:18 UTC, rnjudge approved these changes
Discussed in the Tech call today. Looks good.

2023-11-16 10:35 UTC, merged