The CI run should also commit the json model dump to gh-pages
spdx/spdx-3-model pull request #579
Opened 2023-12-08 09:45 UTC by maxhbr

The spec parser can generate a json representation of the content of the md files. This is for example used in https://github.com/spdx/tools-python/pull/726 and it would be helpful if the CI here would generate and persist these files.

2023-12-08 11:27 UTC, zvr commented
The json dump is arbitrary, completely undocumented, and it should not be used for anything. 
The new parser also generates a json dump, but of course the structure is different.

2023-12-08 11:29 UTC, zvr requested changes

2023-12-08 11:29 UTC, zvr commented on .github/workflows/spec-parser.yml
> +            git add model.ttl model.jsonld context.json model_dump.json auto-generated/
the file is named `model.json` in the new parser

2024-01-16 17:58 UTC, kestewart commented
Per discussion with Joshua in call this is depending on whether the SHACL model is good enough or not.

2024-01-16 18:19 UTC, maxhbr commented
this will be replaced by output or use of https://github.com/JPEWdev/shacl2code

2024-01-16 18:19 UTC, closed without merging