Create an initial browseable model for the gh-pages site.
spdx/spdx-3-model pull request #582
Opened 2023-12-19 15:14 UTC by licquia

Once this is merged, the new browseable model site will live here:

https://spdx.github.io/spdx-3-model/browseable-spec

The long-term goal is to create a complete spec here; the model files are the first step.  Also, any improvements to the look and feel of the model files should be easy to integrate here once available.

2023-12-19 15:43 UTC, zvr requested changes
It was decided that the browsable spec will be in the `spdx-spec` repo, not here.

So all this has to be done there.

2023-12-19 20:43 UTC, licquia commented
That's true, but some parts of this will also have to be done here.

What I've pushed here is a first step, which provides the first pass at a browseable spec.  It's not official, and is certainly not complete, but it does represent putting part of the spec online in a way that's accessible.  My plan is to build from this base.

Do you have specific objections to this approach?

2023-12-22 08:23 UTC, maxhbr commented on browseable/gen-index-page.py
> +#!/usr/bin/env python3
missing license header? I think such code should be under an source code license and not the "Community Specification License 1.0"

2024-01-14 23:01 UTC, goneall commented
@licquia - from our recent discussions, we'll probably move this to the spdx-spec repo.  Should we close this PR?

2024-01-16 14:36 UTC, licquia commented
Yup.  Closing.

2024-01-16 14:36 UTC, closed without merging