Add description to issuingAuthority property
spdx/spdx-3-model pull request #590
Opened 2023-12-23 20:10 UTC by goneall

Fixes one of the TODO's.

2024-01-04 23:00 UTC, kestewart reviewed
Consider adding University as an entity?

2024-01-06 22:55 UTC, goneall commented on model/Core/Properties/issuingAuthority.md
> +The entity may be a government, non-profit or commercial enterprise.  The URI provides a unique identifier for the issuing authority.
Updated to add `educational institution`.

@kestewart - let me know if that works.

2024-01-09 01:00 UTC, kestewart commented on model/Core/Properties/issuingAuthority.md
> +The entity may be a government, non-profit or commercial enterprise.  The URI provides a unique identifier for the issuing authority.
That works.

2024-01-09 19:22 UTC, goneall commented on model/Core/Properties/issuingAuthority.md
> +The entity may be a government, non-profit or commercial enterprise.  The URI provides a unique identifier for the issuing authority.
Could you give it a positive review - one more and I can merge :)

2024-01-11 13:48 UTC, zvr requested changes
The Description is not always supposed to be read together with Summary, so let's repeat some basic stuff.

2024-01-11 13:48 UTC, zvr commented on model/Core/Properties/issuingAuthority.md
> +The entity may be a government, non-profit, educational institution or commercial enterprise.  The URI provides a unique identifier for the issuing authority.
```suggestion
An issuingAuthority is an entity that is authorized to issue identification credentials.

The entity may be a government, non-profit, educational institution, or commercial enterprise.  The URI provides a unique identifier for the issuing authority.
```

2024-01-11 16:15 UTC, zvr approved these changes

2024-01-11 20:43 UTC, kestewart approved these changes
Thanks for the additonal clarification.

2024-01-11 20:43 UTC, merged