GitHub actions improvements
spdx/spdx-3-model pull request #606
Opened 2024-01-23 18:44 UTC by puerco

This PR is a follow-up to #604 to update the workflows improving the way actions are setup in the repo, the summary of the changes is the following:

* Actions are now pinned to hashes instead of tags for security purposes
* Fixes a bug on the validation workflow trigger
* Simplifies the artifact upload in spec-parser to upload everything in one go
* Dropped the hard coded `/tmp` path to use the runner-specific temp directory
* Bump python version in spec-parser to 3.12 to unify it with the version used in valida-pr
* Adds a basic dependabot config to keep the actions up to date
* Normalizes the license boiler plates of the code in the actions config

/cc @zvr @goneall 

Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>

2024-01-23 19:11 UTC, maxhbr commented
the file [.github/workflows/spec-parser.yml](https://github.com/spdx/spdx-3-model/pull/606/files#diff-da81fe6083fdcf8fe39a61ebb4257c51c22a53694b4933938ae2ebbd3a199f27) is about to be deleted. Your changes will soon conflict

2024-01-23 19:41 UTC, puerco commented
@maxhbr do you want me to delete it in this PR?

2024-01-23 19:41 UTC, puerco commented
Opened https://github.com/spdx/spec-parser/pull/90 to fix an unhandled attribut error breaking the check

2024-01-23 20:13 UTC, maxhbr commented
> @maxhbr do you want me to delete it in this PR?

I think that this was the agreement. But it is sad to loose the ontospy generation and the other stuff. Maybe we need to create a ticket to bring that back.

2024-01-23 23:19 UTC, puerco commented
The workflow has been broken for a while and hasn't run for a while (see [this run](https://github.com/spdx/spdx-3-model/actions/runs/7631558311/job/20789764251) for example). I'll fix it so that it can start pushing updates again.

2024-01-24 00:02 UTC, zvr commented
@puerco , I did #604 for a workflow, and that file should be the only one remaining.

Remember, the only action needed is to check the PRs before merging. All generations happen in the spdx-spec repo.

2024-01-24 00:08 UTC, zvr requested changes
Remove the old files and only keep the new workflow.

2024-01-24 00:08 UTC, zvr commented on .github/workflows/validate-pr.yml
> +  pull_request:
I don't think the final `:` is actually needed, if there is nothing underneath in inner levels.

2024-01-24 00:10 UTC, puerco commented
@zvr got it. The question is should we keep the ontospy generation jobs?

If yes, I can fix the current workflow that is broken.

If not, I can simply delete the spec-parser job (keeping only validate-pr).

2024-01-24 00:12 UTC, zvr commented
No, it will run on the spdx-spec repo and publish the results in rdf.spdx.org (or whatever our URI will be).

2024-01-24 07:45 UTC, maxhbr commented
> No, it will run on the spdx-spec repo and publish the results in rdf.spdx.org (or whatever our URI will be).

I disagree slightly and think that some artifacts which are purely built from the model should be generated in the spdx-3-model. But that is more relevant for the shacl and related stuff. Ontospy is an edge case and maybe soon no longer helpful.

2024-01-24 21:58 UTC, goneall requested changes
Let's keep the onotospy for now - no need to remove it until we get everything setup in the new spdx-spec repo.

@licquia - you may want to review updated spec-parser.yml file that @puerco created for us - it has some security improvements we should carry forward to the spdx-spec repo actions.

2024-01-24 21:58 UTC, goneall commented on .github/workflows/spec-parser.yml
>        - name: get spec-parser
This section where we run the spec-parser should be deleted - the current output formats don't currently work with the latest version.

@licquia will add this back to the spec-parser repo

2024-01-24 21:58 UTC, goneall commented on .github/workflows/spec-parser.yml
>        - name: run spec-parser
Same with this section

2024-01-24 21:58 UTC, goneall commented on .github/workflows/spec-parser.yml
> -          python3 ./.github/workflows/test_context.py /tmp/spec-parser.out/context.json
I guess we have to remove this as well

2024-01-24 21:58 UTC, goneall commented on .github/workflows/spec-parser.yml
> -      - uses: actions/upload-artifact@v3
And remove this

2024-01-24 21:58 UTC, goneall commented on .github/workflows/spec-parser.yml
> -          mkdir -p /tmp/auto-generated
I think we should keep this for now until we get the spdx-spec repo up and running

2024-01-24 22:23 UTC, maxhbr commented
> Let's keep the onotospy for now - no need to remove it until we get everything setup in the new spdx-spec repo.


@goneall : we can't keep it, when we drop the generation. To keep that we would need to pin the spec-parser in the old action to an old version.

2024-01-24 22:41 UTC, maxhbr commented
I think that this PR should for now drop `.github/workflows/spec-parser.yml` and lets create a Ticket to rebuild its functionality

2024-01-24 23:16 UTC, goneall commented
> I think that this PR should for now drop .github/workflows/spec-parser.yml and lets create a Ticket to rebuild its functionality

Agree - @puerco - if you could make that change, I can do a quick final review and merge

2024-01-25 00:21 UTC, puerco commented
OK, sounds good :+1: 

I've deleted the spec-parser workflow in a new commit. This should let us rescue the fixed version if we need it.

2024-01-25 00:24 UTC, puerco commented
I think we should delete `test_context.py` as well ?

2024-01-25 07:23 UTC, maxhbr commented
> I think we should delete `test_context.py` as well ?

lets ignore that file for now and just get it merged. I think now everything is green -> merge

2024-01-25 07:23 UTC, maxhbr approved these changes
LGTM

2024-01-25 22:27 UTC, goneall approved these changes
LGTM

2024-01-25 22:28 UTC, merged