Updates integrity verification docs in Core
spdx/spdx-3-model pull request #609
Opened 2024-01-26 13:02 UTC by zvr

This simply updates the definition of `Hash`, `IntegrityMethod`, and `verifiedUsing` in Core to mention other possible verification methods in profiles.

2024-01-26 23:00 UTC, goneall requested changes
I think we need more description on how this would apply to package verification.

If the goal is to provide the reader of the spec with guidance on how to verify a package, just stating that additional methods may be available will not be sufficient.  PR #602 includes enough specifics but my be too constrained.  I would suggest modifying PR #602 to generalize enough to resolve any concerns about over specifying the algorithm.

2024-01-30 21:30 UTC, zvr commented on .github/workflows/validate-pr.yml
> +name: validate PR
Of course not. Sorry, @goneall

2024-01-31 04:01 UTC, maxhbr commented
@zvr This PR is conflicting

2024-01-31 06:58 UTC, zvr commented
@maxhbr yes, because of my error of including the workflow file.

Unfortunately I  won't be able to correct it myself for a while...

2024-03-26 16:59 UTC, kestewart commented
Moving this to 3.1 - since unlikely to be a breaking change (extending vocabulary options).

2024-03-26 23:59 UTC, zvr commented
@kestewart conflicts fixed.

The workflow file is the same as the one present making it a no-op (I don't know how to actually remove it).

As explained in the tech call, this simply adds a sentence to three descriptions, that profiles may provide additional integrity methods.

2024-04-14 23:02 UTC, kestewart approved these changes

2024-04-14 23:05 UTC, kestewart commented
@goneall - can you see if Alexios' updates have fixed the issues you flagged?   If it's good from your perspective, we should probably include it.    If not,  please move it back to 3.1 (I moved it to 3.0, so it would be considered).

2024-04-15 01:23 UTC, goneall approved these changes
Agree with Kate that with the additional work in verification, this documentation is now sufficient.

2024-04-15 01:24 UTC, merged