Update LifecycleScopeType.md
spdx/spdx-3-model pull request #615
Opened 2024-01-29 21:30 UTC by kestewart

Update the descriptions for the LifecycleScopedRelationship Enumerations.  

Note that this parameterizes historical relationships, like DEV_DEPENDENCY_OF, BUILD_DEPENENCY_OF, RUNTIME_DEPENDENCY_OF, etc. and pelaces them with depends_on with this lifecycleScopeType.

Signed-off-by: Kate Stewart <kstewart@linuxfoundation.org>

2024-01-29 23:00 UTC, goneall requested changes
A set of suggestions to make the language more consistent by referring to the "phase" of the lifecycle in the enumeration comments.

2024-01-29 23:00 UTC, goneall commented on model/Core/Vocabularies/LifecycleScopeType.md
> +- runtime: A relationship has specific context implications when an element is executing.
```suggestion
- runtime: A relationship has specific context implications during the execution phase of an element.
```

2024-01-30 17:36 UTC, kestewart commented
@goneall - I don't really think "phase" is really needed, but I don't feel strongly enough to argue.   Applied your changes.   Can you please re-review.

2024-01-30 23:50 UTC, goneall approved these changes
LGTM

2024-01-31 14:34 UTC, nishakm approved these changes

2024-01-31 18:05 UTC, merged