Updated model diagrams to align with state of specification as of 02-15-24
spdx/spdx-3-model pull request #643
Opened 2024-02-16 15:02 UTC by sbarnum

2024-02-16 20:43 UTC, kestewart requested changes
On the Core+Software Diagram,   plase remove the WGs and Exmaples part of it.  It contains stale data, and may cause confusion.

2024-02-16 20:44 UTC, kestewart commented
Also please add your - "Signed-off-by: Sean Barnum <email>" to the comments (should be on the commit, but that's harder to do).

2024-02-16 20:45 UTC, goneall requested changes
A few requested changes

2024-02-16 21:49 UTC, kestewart commented on model Core+Software.png
packageVerificationCodeExcluededFile was merged.

2024-02-17 18:18 UTC, goneall commented on model Core+Software.png
Never mind - it looks like in the diagram we don't use the xsd types

2024-02-17 18:45 UTC, goneall commented on model Core+Software.png
Updated in the latest commit

2024-02-17 18:45 UTC, goneall commented on model Core+Software.png
Updated in the latest commit

2024-02-17 18:45 UTC, goneall commented on model Core+Software.png
Updated in the latest commit

2024-02-17 20:21 UTC, kestewart approved these changes
Changes look good to me.

Sean reviewed and added the last commit. 

Based on this,  and the other commit from Gary,  I'm going to go ahead and merge these.

2024-02-17 20:24 UTC, kestewart requested changes
Sean,  the PackageVerificationCode should have an algorithm on it.   Can you delete your last commit.

2024-02-17 20:35 UTC, kestewart approved these changes

2024-02-17 20:36 UTC, merged