Update VexVulnAssessmentRelationship.md
spdx/spdx-3-model pull request #648
Opened 2024-02-20 05:25 UTC by VenkatTechnologist

To be precise, VEX as such does not have a version of its own at least as of now. The version (1.0.0 released in April 2023) is for minimum requirements of data elements. Hence suggest this field to reflect precisely what the version field means.

2024-02-20 05:30 UTC, VenkatTechnologist commented
There is a key error, and it looks like there are places in code to change if this change is accepted.

2024-02-20 11:25 UTC, zvr requested changes
If there is need for the property to be renamed, the changes must also be made in the [property definition](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Properties/vexVersion.md) as well.

2024-02-20 13:25 UTC, VenkatTechnologist commented
> If there is need for the property to be renamed, the changes must also be made in the [property definition](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Properties/vexVersion.md) as well.

Updated properties too, and created a separate pull request for that. Note that default version should be "1.0.0", not zero. Mentioned the same in the property description.

2024-04-03 19:01 UTC, goneall commented
@VenkatTechnologist - if PR #649 is still valid - please add this change to PR #649 and close this one

2024-04-08 19:40 UTC, jeff-schutt requested changes
IMO we should not change the name of this property. Reason explained [here](https://github.com/spdx/spdx-3-model/pull/649#pullrequestreview-1987271049).

2024-04-08 20:53 UTC, puerco commented
+1 for not changing this property is not the version of vex.

2024-04-10 19:19 UTC, rnjudge commented
This PR should be merged with https://github.com/spdx/spdx-3-model/pull/649. Closing this one so we can continue discussion on 649.

2024-04-10 19:19 UTC, closed without merging