Change isDirectory to fileKind enumeration
spdx/spdx-3-model pull request #666
Opened 2024-03-12 18:15 UTC by goneall

Fixes #630

Note that fileKind was choosen since fileType is already in use

2024-03-12 19:06 UTC, zvr requested changes

2024-03-12 19:06 UTC, zvr commented on model/Software/Classes/File.md
>    - type: xsd:boolean
Surely not `boolean` ?!?

2024-03-12 22:27 UTC, goneall commented on model/Software/Classes/File.md
>    - type: xsd:boolean
Good catch @zvr - fixed

2024-03-19 16:49 UTC, kestewart requested changes
Couple of ambiguities should be cleared up.  See comments.

2024-03-19 16:49 UTC, kestewart commented on model/Software/Vocabularies/FileKindType.md
> +- file: The file represents a single file.
Can we make it explicit, that if the field is not specified, the assumption is that fileKind is "file".

2024-03-19 16:49 UTC, kestewart commented on model/Software/Properties/fileKind.md
> +An SPDX file may represent a file on disk or a directory of files.  In the future, this may be extended to other kinds (e.g. network based files).
file could be in memory not just "disk".... probably want to rephrase to something like: 
"represent a file on disk" to "represent a specific file"

2024-03-22 04:35 UTC, goneall commented
@zvr @kestewart - updated per comments - please review or request changes

2024-03-22 19:02 UTC, kestewart approved these changes
Thanks Gary.  Both issues are resolved. 
Good to merge from my perspective.

2024-03-22 19:02 UTC, merged