add SoftwareDependencyRelationship to Software profile
spdx/spdx-3-model pull request #69
Opened 2023-01-19 10:35 UTC by armintaenzertng

also add the three software dependency vocabularies `DependencyLinkType`, `DependencyRequirement` and `DependencyScope` according to https://github.com/spdx/spdx-3-model/blob/main/model.png

Signed-off-by: Armin Tänzer <armin.taenzer@tngtech.com>

2023-03-28 17:26 UTC, maxhbr commented
Kate wants to give feedback to the SoftwareDependencyRelationship concept as it is expressed in the drawio diagram and this is blocking this PR.

2023-03-30 15:11 UTC, kestewart commented
@iamwillbar - can you please plan on making next Tuesday's call, as I think it will take both of us to work through this.
I think there are some use cases the revised model will have trouble figuring out how to specify, so need to talk this out.

2023-03-30 15:12 UTC, kestewart requested changes
Some concerns about the underlying model.   Needs further discussion.

2023-04-19 05:57 UTC, armintaenzertng commented
@kestewart, I updated the PR according to yesterday's tech team discussion. I'm not sure whether `DependencyConditionalityType` belongs in `Software` or if it is a general enough concept that it would be reused in other profiles.

2023-04-29 10:38 UTC, kestewart approved these changes
We need to fill in the TODOs, but this relects my understanding of the decisions made in the tech team meeting.   Thanks!

2023-04-29 10:38 UTC, merged