Add cwe as ExternalIdentifierType
spdx/spdx-3-model pull request #711
Opened 2024-04-10 22:21 UTC by rnjudge

Per discussion in the April 10 Security call, this commit adds cwe (common weakness enumeration) as an ExternalIdentifierType.

Closes https://github.com/spdx/spdx-spec/issues/102

2024-04-10 23:26 UTC, puerco requested changes
I think this is not correct. 

A CWE string is not an identifier like a CVE number is, for example. A vulnerability can have as its root cause more than one CWE. 

The CWE strings are a reference to a catalog of vulnerability categories. As per your definitions in #710, I think an ExternalRef fits better.

2024-04-11 15:23 UTC, rnjudge commented
Thanks @puerco! PR updated.

2024-04-11 17:03 UTC, puerco approved these changes
Awesome, thanks!

2024-04-13 01:47 UTC, goneall approved these changes
LGTM

2024-04-13 01:47 UTC, merged