Add Contributing.md
spdx/spdx-3-model pull request #75
Opened 2023-01-24 00:37 UTC by rnjudge

The tech team agreed to a profile-specific contributing process at the meeting on 2023-01-17. Document that decision here for reference moving forward.

Signed-off-by: Rose Judge <rjudge@vmware.com>

2023-01-24 00:37 UTC, rnjudge commented
@goneall @kestewart @zvr please review for accuracy :)

2023-01-24 02:31 UTC, goneall requested changes
Thanks @rnjudge - this was on my list to do today, but just didn't get to it.

Just a couple suggestions.

2023-01-24 02:31 UTC, goneall commented on Contributing.md
> +There are multiple profiles being developed in parallel for the SPDX 3.0 Model. During this initial phase of development, each profile working group will contribute changes to its own branch in this
Suggest changing `should be committed to the` to `should be submitted as a change request to the`

2023-01-24 02:31 UTC, goneall commented on Contributing.md
> +Once alerted, the SPDX tech group will review and provide feedback. Once profile proposals have been reviewed and approved, the profile-specific branch will be merged to a general `development` branc
Suggest changing `along with the other finished profile models.` to `along with the other reviewed profile models.`

2023-01-24 18:28 UTC, seabass-labrax approved these changes
Looks good to me! :smiley:

PS. The difference between namespaces and profiles is still not clear, but that's not an issue with this pull request. However, this document may need to be changed when we determine the correct terminology.

2023-01-24 18:28 UTC, goneall approved these changes
LGTM

2023-01-24 18:36 UTC, jeff-schutt reviewed
See proposed change. Otherwise LGTM!

2023-01-24 19:17 UTC, rnjudge commented on Contributing.md
> +There are multiple profiles being developed in parallel for the SPDX 3.0 Model. During this initial phase of development, each profile working group will contribute changes to its own branch in this
works for me!

2023-03-01 16:35 UTC, kestewart commented
There are a couple of updates to make to the profile set, but what's there is a good starting point.   Merging this, and will propose further updates.

2023-03-01 16:36 UTC, kestewart approved these changes

2023-03-01 16:36 UTC, merged