NamespaceMap: Remove TODO and fix caps
spdx/spdx-3-model pull request #796
Opened 2024-07-02 17:12 UTC by bact

The URLs are already updated.

(although they are all pointing directly to the repo: https://github.com/spdx/spdx-3-model/ - it this something we are preferred?)

2024-07-22 22:02 UTC, goneall commented
@bact I personally think we should point to the generated mkdocs HTML pages rather than the repo.  We can discuss on the next tech call.

2024-07-22 22:03 UTC, kestewart approved these changes
Thanks!

2024-07-26 14:53 UTC, bact commented
> @bact I personally think we should point to the generated mkdocs HTML pages rather than the repo. We can discuss on the next tech call.

@goneall Our current "Model and serializations" page at https://spdx.github.io/spdx-spec/v3.0/serializations/ does not has information about NamespaceMap. While our "Notes on Serialization" at https://github.com/spdx/spdx-3-model/tree/main/serialization#readme has it.

2024-07-30 16:33 UTC, goneall commented
Discussed on 30 July 2024 tech call:
- Agreed we should point to the HTML - required for ISO
- We need to open a pull request to add the information to the spec serialization section, then change the links in this PR

2024-07-31 11:49 UTC, bact commented
>     * Agreed we should point to the HTML - required for ISO
> 
>     * We need to open a pull request to add the information to the spec serialization section, then change the links in this PR

A PR #1016 is open.

2024-08-06 16:52 UTC, kestewart approved these changes

2024-08-07 14:43 UTC, zvr requested changes

2024-08-07 14:43 UTC, zvr commented on model/Core/Classes/NamespaceMap.md
> +[Model and Serializations](../../../docs/serializations.md)
```suggestion
the [Model and Serializations](../../../docs/serializations.md) clause
```

2024-08-07 14:43 UTC, zvr commented on model/Core/Classes/NamespaceMap.md
> +and the various serialization format-specific .md files in
```suggestion
and the various serialization format-specific files in
```

2024-08-08 16:23 UTC, closed without merging

2024-08-08 21:09 UTC, bact commented
@zvr @kestewart this PR is automatically closed by GitHub because the description of PR #1016 has the word "fix" before this PR number. Do you mind to reopen this please? Thank you. This is probably one of the few last PRs for 3.0.1 model.

2024-08-09 10:52 UTC, bact commented
Reopened as #821, with a new fix