Update cpe23 link in ExternalIdentifierType
spdx/spdx-3-model pull request #806
Opened 2024-07-25 10:46 UTC by bact

- Make URL matched with one in the References chapter (see https://github.com/spdx/spdx-spec/pull/1006 )
- Make URLs clickable

2024-07-26 09:49 UTC, zvr requested changes
Links should not be visible (I only did a couple)

2024-07-26 09:49 UTC, zvr commented on model/Core/Vocabularies/ExternalIdentifierType.md
> +- cpe22: Common Platform Enumeration Specification 2.2 <https://cpe.mitre.org/files/cpe-specification_2.2.pdf>
```suggestion
- cpe22: [Common Platform Enumeration Specification 2.2](https://cpe.mitre.org/files/cpe-specification_2.2.pdf)
```

2024-07-26 09:49 UTC, zvr commented on model/Core/Vocabularies/ExternalIdentifierType.md
> +- cve: Common Vulnerabilities and Exposures identifiers, an identifier for a specific software flaw defined within the official CVE Dictionary and that conforms to the CVE specification as defined by
```suggestion
- cve: Common Vulnerabilities and Exposures identifiers, an identifier for a specific software flaw defined within the official CVE Dictionary and that conforms to the [CVE specification](https://csrc.nist.gov/glossary/term/cve_id).
```

2024-07-26 10:40 UTC, bact commented
> Links should not be visible (I only did a couple)

Thanks. I have made all of them invisible now.

2024-07-30 04:41 UTC, goneall approved these changes
LGTM

2024-07-30 16:35 UTC, zvr approved these changes

2024-07-30 16:35 UTC, merged