Revert PR 845 - allow empty Bom and SpdxDocument element lists
spdx/spdx-3-model pull request #853
Opened 2024-08-13 17:36 UTC by goneall

This is based on the discussion on the 13 August 2024 tech call.

Adding the restrictions in the patch release would be a breaking change for some of the known tooling and it was agreed that adding the restrictions was not necessary.

The decision on the tech call was to allow empty root elements as well as empty element lists for both Bom and SpdxDocuments.

2024-08-13 17:47 UTC, zvr commented
Oh! :-(

That's too bad.

Then the Lite profile should be updated (in both the model and the spec), since they still have this requirement.

2024-08-13 20:15 UTC, goneall commented
@zvr - I just added a commit to update the Lite profile in the model (this) repo.  I looked at the spec Annex for lite, and it looks OK as is (already has the minimums defined for root and element).

2024-08-13 20:32 UTC, zvr requested changes
To be consistent with the restrictions above.

(yes, I know, the old stuff in the comment was in the old style)

2024-08-13 20:32 UTC, zvr commented on model/Lite/Lite.md
> +1. The mincount for `/Software/Sbom/rootElement` is 1
```suggestion
1. The mincount for `element` is 1
1. The mincount for `rootElement` is 1

For a `/Software/Sbom` to be conformant with this profile, the following has to hold:
1. The mincount for `element` is 1
1. The mincount for `rootElement` is 1
```

2024-08-13 21:43 UTC, zvr approved these changes

2024-08-14 12:53 UTC, bact approved these changes
Looks good. Implemented what was agreed in the meeting.

2024-08-14 18:09 UTC, merged