Add /Core/Individuals/SpdxOrganization
spdx/spdx-3-model pull request #880
Opened 2024-09-11 22:53 UTC by bact

- Add a named individual SpdxOrganization
- This individual is meant to be used for CreationInfo inside named individuals
- This PR should be review together with https://github.com/spdx/spec-parser/pull/154
- Note that currently "## Property Values" is not processed, another PR in spec-parser is needed for spdxId, etc to be included in SpdxOrganization

2024-09-12 06:14 UTC, zvr requested changes

2024-09-12 06:14 UTC, zvr commented on model/Core/Individuals/SpdxOrganization.md
> +- spdxId: https://spdx.org/
No, there is no `spdxId` property.

Use `IRI` in Metadata as in https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Individuals/NoneLicense.md

2024-09-12 06:14 UTC, zvr commented on model/Core/Individuals/SpdxOrganization.md
> +An Individual Value for Organization representing the SPDX Project.
```suggestion
An Organization representing the SPDX Project.
```

2024-09-12 06:14 UTC, zvr commented on model/Core/Individuals/SpdxOrganization.md
> +SpdxOrganization is used by named individuals for their creationInfo.
```suggestion
SpdxOrganization is an Organization representing the SPDX Project. It is by definition the creator of all individuals defined by the SPDX Project. These individuals include licences and exceptions defined in the SPDX License List, as well as individuals defined in the specification.
```

2024-09-12 14:08 UTC, goneall commented
I wonder if we should make the IRI more specific - for example, `https://spdx.org/organization`

I could create a web page with a redirect to https://spdx.dev/about/overview/

2024-09-12 14:34 UTC, zvr commented
I am confused... Don't you think that "https://spdx.org" is the right identifier for the SPDX project?

I mean, for another example, Intel has tons of pages describing the company (equivalent to "About us"), but the identifier to be used in such a context will definitely be https://www.intel.com/.

It will also be useful to others who would want to refer to the SPDX project to be able to simply use `<https://spdx.org>` as an Element identifier.

2024-09-13 03:15 UTC, goneall approved these changes
LGTM

2024-09-13 03:17 UTC, goneall commented
> I am confused... Don't you think that "https://spdx.org" is the right identifier for the SPDX project?
> 
> I mean, for another example, Intel has tons of pages describing the company (equivalent to "About us"), but the identifier to be used in such a context will definitely be https://www.intel.com/.
> 
> It will also be useful to others who would want to refer to the SPDX project to be able to simply use `<https://spdx.org>` as an Element identifier.

My suggest is based on "https://spdx.org" being the prefix for the SPDX RDF ontology which may be somewhat confusing.

That said, I'm OK going with the proposed URI.

I've approved the PR - so feel free to merge if you'd like to go with the current URI.

2024-09-13 10:10 UTC, merged

2024-09-13 11:38 UTC, bact commented
`SpdxOrganization` spec is now available at
https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Individuals/SpdxOrganization/