Add Build profile
spdx/spdx-3-model pull request #91
Opened 2023-02-28 17:54 UTC by lumjjb

Add build profile definitions to spdx-model-3

2023-04-03 15:13 UTC, armintaenzertng requested changes
Hi, thanks for bringing in the build profile! :)
I have a few remarks that are mainly concerned with the ability to automatically parse the markdown files.

2023-04-03 15:13 UTC, armintaenzertng commented on model/Build/Classes/Build.md
> +  - type: xsd:DateTime
```suggestion
  - type: xsd:dateTime
```

2023-04-03 15:13 UTC, armintaenzertng commented on model/Build/Vocabularies/BuildTypeVocab.md
This Vocabulary is not used anywhere and the markdown file has several issues. Is this still intended to be used?
It looks like a collection of examples to me, maybe they could be moved over to the description of `buildType.md`?

2023-04-03 15:13 UTC, armintaenzertng commented on model/Build/Classes/Build.md
@goneall: I'm not sure about this, but as you raised concerns over multiple properties with the same name, do you think it will be problematic if a class has the same name as a profile?

2023-04-04 16:45 UTC, nishakm commented on model/Core/Vocabularies/RelationshipType.md
> +- buildToolOf: Build tool used in the build instance
This already exists in 2.3. So this is OK.

2023-04-04 16:49 UTC, nishakm commented on model/Core/Vocabularies/RelationshipType.md
> +- buildChildOf: Build instance that was created from another build instance
Use ancestor relationship. One ancestor with lots of decendents.

2023-04-04 16:50 UTC, nishakm commented on model/Core/Vocabularies/RelationshipType.md
> +- buildOnBehalfOf: Person for which buildInvokedBy is acting on behalf of
Clarify that this is "Actor". Also need to clarify constraints on each of the relationships.

2023-04-04 16:53 UTC, nishakm commented on model/Core/Vocabularies/RelationshipType.md
> +- buildOnBehalfOf: Person for which buildInvokedBy is acting on behalf of
Why not properties for buildInvokedBy and buildOnBehalfOf?

2023-04-04 17:09 UTC, zvr commented on model/Build/Vocabularies/BuildTypeVocab.md
> +- Type: URI
xsd:anyURI

2023-04-04 17:14 UTC, nishakm reviewed
- Commit suggestions
- Use builtDate instead of endTime. Or buildStart and buildEnd

2023-04-04 17:20 UTC, nishakm commented on model/Build/Classes/Build.md
> +  - type: xsd:map<string>string
Perhaps define a class in Core called "Dictionary" and Parameters can be of type Dictionary.

2023-04-06 23:38 UTC, nishakm commented
I think this is ready to merge @goneall

@armintaenzertng I'm deferring the question about whether it's OK to give the class and the profile the same name "Build" and what DataType to use for key-value pairs. From this week's tech call, these are going to be further discussed.

2023-04-07 00:39 UTC, goneall commented
Thanks @nishakm - I'll merge these in.

@armintaenzertng - for the remaining questions/issue please open a new issue or PR to track.

2023-04-07 00:39 UTC, merged