use relative path syntax
spdx/spdx-3-model pull request #913
Opened 2024-11-14 02:12 UTC by ilans

As per: https://github.com/spdx/spdx-3-model/issues/910

Require filenames to use the relative path syntax.

2024-11-14 07:26 UTC, bact commented
To remove the entire RFC is a big change, considering this one already passed the OMG review. At this stage, I understand that the change should be minimal and as necessary. 

And the syntax for filename in RFC is more than just the prefix.

2024-11-14 07:28 UTC, bact requested changes

2024-11-14 07:28 UTC, bact commented on model/Core/Properties/packageVerificationCodeExcludedFile.md
> -[RFC 3986 Uniform Resource Identifier (URI): Generic Syntax](https://datatracker.ietf.org/doc/rfc3986/)
Keep RFC please. 

Or defer this change to the next MINOR version update, which is 3.1.

2024-11-14 08:47 UTC, zvr commented
Sorry, @bact, I must be misunderstanding something.

How is any of the RFC relevant?  The RFC talks about URIs, this field accepts filenames.

2024-11-14 19:05 UTC, goneall commented
Agree with @zvr and @ilans - we should remove this reference.

@zvr @ramartin - What will this do to the ISO / OMG review if we merge this in?

2024-11-14 19:05 UTC, kestewart approved these changes
Not sure why URI syntax is relevant to file name syntax, not sure why it was included initially.

2024-11-14 19:07 UTC, goneall approved these changes
Agree with the change - pending feedback from @zvr and @bobmartin3000 on impact to OMG review process

2024-11-14 19:33 UTC, bact commented
I'm fine to have the change. My concern this is clearly not a change in a category of typo.

The URI can be a filename, so there is no harm keeping it.

But there can be a potential harm of prolonging the OMG review process.
If there's not the case, I don't see problem to have this change go to 3.0.1.

We defer a lot of issues and PRs in the past few months because of that OMG review reason.
I'm just try to keep it consistent that way. This is my understanding.

2024-11-14 19:47 UTC, bact commented
This is Bob username @bobmartin3000

2024-11-14 19:52 UTC, bact approved these changes
If the process allows this to be in 3.0.1, please proceed.

2024-11-15 12:40 UTC, bobmartin3000 commented
Functionally we aren't changing anything with the removal of the reference to the RFC. I'm okay with the change but it is stretching the editorial change label.

2024-11-15 12:40 UTC, bobmartin3000 approved these changes
LGTM.

2024-11-15 15:55 UTC, merged