SoftwareArtifact as range for assessedElement
spdx/spdx-3-model pull request #933
Opened 2024-12-04 08:00 UTC by ilans

See: https://github.com/spdx/spdx-3-model/issues/911

2024-12-04 12:04 UTC, bact commented
- [  ] To update CHANGE LOG
- [  ] To update diagrams

2024-12-04 14:53 UTC, goneall approved these changes
LGTM - Thanks @ilans

2024-12-04 15:27 UTC, zvr commented
I've just realized that this introduces a dependency between the Security profile and the Software one. I don't know whether we had it before. Are we OK with this ?
@goneall @ilans @kestewart

2024-12-04 15:50 UTC, zvr commented
So, I've just checked. The dependency wasn't there before.
Can we simply make it `/Core/Artifact` to spare us long(er) discussions and more possible changes?

2024-12-04 21:22 UTC, goneall requested changes
Per Alexios' suggestion, added suggestion changing to `/Core/Artifact`

2024-12-04 21:22 UTC, goneall commented on model/Security/Classes/VulnAssessmentRelationship.md
> +  - type: /Software/SoftwareArtifact
```suggestion
  - type: /Core/Artifact
```

2024-12-04 21:22 UTC, goneall commented on model/Security/Properties/assessedElement.md
> +- Range: /Software/SoftwareArtifact
```suggestion
- Range: /Core/Artifact
```

2024-12-05 17:56 UTC, goneall commented on model/Security/Classes/VulnAssessmentRelationship.md
> +  - type: /Software/SoftwareArtifact
From call on 5 Dec - agreed to leave as SoftwareArtifact

2024-12-05 17:57 UTC, goneall approved these changes

2024-12-05 17:57 UTC, goneall commented on model/Security/Properties/assessedElement.md
> +- Range: /Software/SoftwareArtifact
From call on 5 Dec - agreed to leave as SoftwareArtifact

2024-12-05 17:57 UTC, bact approved these changes

2024-12-05 17:57 UTC, merged